name: Label Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    name: "Label Pull Request"
    permissions:
      contents: read
      issues: write
      pull-requests: write
    # 5398ca6b022453afbddfc9ed857398588669197b is launch-workflows tag 0.16.2
    uses: launchbynttdata/launch-workflows/.github/workflows/reusable-pr-label-by-branch.yml@5398ca6b022453afbddfc9ed857398588669197b
    secrets: inherit # pragma: allowlist secret
