name: Publish Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-on-merge:
    name: "Create and Publish Release on Merge"
    permissions:
      contents: write
      pull-requests: write
    # 5398ca6b022453afbddfc9ed857398588669197b is launch-workflows tag 0.16.2
    uses: launchbynttdata/launch-workflows/.github/workflows/reusable-release-on-merge.yml@5398ca6b022453afbddfc9ed857398588669197b
    secrets: inherit # pragma: allowlist secret
